### ISSUE TITLE
Issue/question with miZy-spi-image-builder

### ISSUE THREAD

**Issue by romankk** [hyphop/miZy-spi-image-builder#1]
@hyphop 
Hi,
Thank you for your effort in building SPI image for Orange PI
I was trying to build image for my newly purchased Orange PI Zero Allwinner H2+
I installed successfully Armbian stable and update to latest  ARMBIAN 5.36 user-built Ubuntu 16.04.3 LTS 3.4.113-sun8i   
Once I loged in I followed your instructions:
`mkdir /tmp/zero_builder
cd /tmp/zero_builder
git clone https://github.com/hyphop/miZy-spi-image-builder.git
cd miZy-spi-image-builder`
Now when I'm trying to run following 
`img_size=16M ./miZy_spi_image_builder`
I get following
`[i] ./ miZy_spi_image_builder => CONF: ./miZy_spi_image_builder.conf
[i] 16M bytes => firmwares/orange_pi_zero_hyphop_mizy_spi_flash_demo-%s%s.bin
[i]     MTD_PART 0xHEX_SIZE( DEC_SIZE){ USED_SZ} FILES
Died at ./miZy_spi_image_builder line 237.
[e] file "" not found
ERR: 2
`

I tried to run
`./miZy_spi_image_builder`

with the same result
`[i] ./ miZy_spi_image_builder => CONF: ./miZy_spi_image_builder.conf
[i] 8M bytes => firmwares/orange_pi_zero_hyphop_mizy_spi_flash_demo-%s%s.bin
[i]     MTD_PART 0xHEX_SIZE( DEC_SIZE){ USED_SZ} FILES
Died at ./miZy_spi_image_builder line 237.
[e] file "" not found
ERR: 2
`
What I'm missing or doing wrong?

**Comment by hyphop** [comment]
1) u can make image directly on your machine   (no need armbian and zero board)
2) and u need all required files for firmware building
ls -1 
boot.all.cmd
boot.all.env
boot.spi.env
boot.spi.scr
orangepizero.bin
script.bin
u-boot-mizi.bin
uImage.gzip
uImage.lzma
uImage.lzo
uInitrd.sfs

**Comment by ohmex** [comment]
Can you throw some light on how to create these files.
I am also finding trouble creating "uInitrd.sfs"

**Comment by hyphop** [comment]
ok i have write some wiki about this 
https://github.com/hyphop/miZy-spi-image-builder/wiki/miZy-ramdisk-image
for  personal consultation welcome to https://hyphop.github.io/donate/
