### ISSUE TITLE
missing files bin.local

### ISSUE THREAD

**Issue by JefkeB** [hyphop/miZy-spi-image-builder#2]
Hi,

trying to build a spi image with the script.
It complains about 'file "boot.all.cmd"  not found'.
After cloning the repository only links to files are in bin.local and they are pointing to locations not available, like '../../miZy/boot.all.cmd'
Please assist me in solving this ...

btw
Plan is to start using your small Linux on a orange pi zero running from an 16MB spi flash as a base for restoring an old internet radio (Tangent Quattro MK II)

Thanks,
J

**Comment by hyphop** [comment]
ok plz wait one tow days i will write more detailed manuals
about how to build this !

**Comment by hyphop** [comment]
hi again,
plz check this files (need for build any mizy image)
https://github.com/hyphop/miZy-spi-image-builder/blob/master/bin.examples/boot.fel.cmd
https://github.com/hyphop/miZy-spi-image-builder/blob/master/bin.examples/boot.fel.env
another files 
u can generate or extract from any mizy images via `hybrid` - https://github.com/hyphop/miZy-spi-image-builder/blob/master/tools/hybrid

welcome

**Comment by JefkeB** [comment]
Hi Art,

Will try it this weekend and let you know.
Thank you very much for spending time on helping me.

J
